modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "advancedenderite"
version = "${version}"
displayName = "AdvancedEnderite"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.advancedenderite]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.187,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advancedenderite]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advancedenderite]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
